name: dailytracker
description: "Daily Habit Tracker - Theo dõi thói quen hằng ngày"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  lottie: ^3.1.3
  table_calendar: ^3.1.2
  flutter_slidable: ^3.1.1
  percent_indicator: ^4.2.3
  flutter_animate: ^4.5.0
  timezone: ^0.9.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.4.10
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/db/
